version: "3"

services:
  app:
    build: .
    container_name: controle-obras-api
    volumes:
      - .:/home/dotnet/app
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1q2w3e4r@#=
    ports:
      - "1433:1433"
    networks:
      - mynetwork
    volumes:
      - ./docker/data:/var/opt/mssql

networks:
  mynetwork:
